#!/usr/bin/env bash
echo 
echo Updating Total Course Points...
python3.7 -m pip install TotalCoursePoints --upgrade
echo 
echo Running the autograder...
# python3.7 -u main_setup.py
python3.7 -u main.py
